### ISSUE TITLE
master-depls/cf is swallowing cloudcontroller error logs into: An unknown error occurred

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1229]
### Expected behavior

* As a paas-templates operator 
* In order to be able to diagnose errors returned by cloudfoundry
* I need the error message description to be returned

### Observed behavior
 
```
$ cf update-service-broker osb-cmdb-broker-cf-z2 user ... https://redacted-domain.org

Updating service broker osb-cmdb-broker-cf-z2 as admin...

Job (22f929e2-0688-4a6d-a4f6-becbda587af6) failed: An unknown error occurred.

FAILED
```

### Workaround

```
$bosh ssh cc-worker/0

$ cat /var/vcap/sys/log/cloud_controller_worker/cloud_controller_worker.log

{"timestamp":"2021-06-25T16:09:30.566352033Z","message":"about to run job 
VCAP::CloudController::V3::UpdateBrokerJob","log_level":"info","source":"cc.background","data":{"request_guid":"c7023c8d-
0182-4867-6998-a24d695be551::e6338ebf-e693-4421-8e43-
a67a1fe063ba"},"thread_id":66300,"fiber_id":66480,"process_id":5,"file":"/var/vcap/data/packages/cloud_controller_ng
/0436f07256a6c31ee71e53cedf2989199baefa96/cloud_controller_ng/app/jobs
/logging_context_job.rb","lineno":16,"method":"block in perform"}             

{"timestamp":"2021-06-25T16:09:31.393946181Z","message":"Request failed: 500: {\"error_code\"=>\"UnknownError\", 
\"description\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"description\"=>\"Plan names must 
be unique within a service. Service my-service already has a plan named XXX\", \"error_code\"=>\"CF-InvalidServiceBroker\", 
\"backtrace\"=>[\"/var/vcap/data/packages/cloud_controller_ng/0436f07256a6c31ee71e53cedf2989199baefa96
/cloud_controller_ng/app/jobs/v3/services/update_broker_job.rb:74:in `rescue in perform'\", \"/var/vcap/data/packages
/cloud_controller_ng/0436f07256a6c31ee71e53cedf2989199baefa96/cloud_controller_ng/app/jobs/v3/services
/update_broker_job.rb:66:in `perform'\", \"/var/vcap/data/packages/cloud_controller_ng
/0436f07256a6c31ee71e53cedf2989199baefa96/cloud_controller_ng/app/jobs/v3/services/update_broker_job.rb:17:in 
`perform'\",
```

### Fix outline

* [ ] bump capi
* [ ] fix side effect on coab annotations https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/404

### References

The problem was available in https://github.com/cloudfoundry/cloud_controller_ng/issues/2147 which is fixed in capi 1.108.0 https://github.com/cloudfoundry/capi-release/releases/tag/1.108.0 or later, 1.109 in https://github.com/cloudfoundry/cf-deployment/releases/tag/v16.11.0

### Affected releases

* v52.0.2
* v51.5
* earlier versions

**Comment by gberche-orange** [comment]
Potential fix in https://github.com/cloudfoundry/cloud_controller_ng/pull/2537 being drafted, not yet released

**Comment by poblin-orange** [comment]
to check with v54 cf-deployment 0.18.0

**Comment by o-orand** [comment]
Fixed in v54
