### ISSUE TITLE
Ksqldb overload and replica fail over issue

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1727]
### Expected behavior

* As a paas-templates operator 
* In order to leverage ksqldb
* I need to have ksqldb reliably handle requests

### Observed behavior
 
* timeouts during ksqlmigration requests
* UnknownHostException and ksql standby / congestion logs

```
    │ cp-ksql-server [2022-09-19 09:13:15,371] INFO [Consumer clientId=_confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a5256ae2-StreamThread-4-consumer, gro │

    │ cp-ksql-server org.apache.kafka.common.errors.TimeoutException: Failed to send request after 30000 ms.                                                                                                  │

    │ cp-ksql-server [2022-09-19 09:13:16,771] INFO [Consumer clientId=_confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a5256ae2-StreamThread-4-consumer, gro │

    │ cp-ksql-server org.apache.kafka.common.errors.DisconnectException                                                                                                                                       │

    │ cp-ksql-server [2022-09-19 09:13:17,489] INFO Reporting thread saturation 0.002499729125013544 for _confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a52 │

    │ cp-ksql-server [2022-09-19 09:13:17,491] INFO Reporting thread saturation 0.003030600481803309 for _confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a52 │

    │ cp-ksql-server [2022-09-19 09:13:17,492] INFO Reporting thread saturation 0.002626380675347633 for _confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a52 │

    │ cp-ksql-server [2022-09-19 09:13:17,493] INFO Reporting thread saturation 0.0026034401864946572 for _confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a5 │

    │ cp-ksql-server [2022-09-19 09:13:17,493] INFO Reporting query saturation 0.003030600481803309 for CTAS_MIGRATION_SCHEMA_VERSIONS_1 (io.confluent.ksql.utilization.PersistentQuerySaturationMetrics:213) │

    │ cp-ksql-server [2022-09-19 09:13:17,494] INFO reporting node-level saturation 0.003030600481803309 (io.confluent.ksql.utilization.PersistentQuerySaturationMetrics:157)                                 │

    │ cp-ksql-server [2022-09-19 09:13:38,605] INFO stream-thread [_confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a5256ae2-StreamThread-4] Processed 0 tota │

    │ cp-ksql-server [2022-09-19 09:13:47,719] INFO [Consumer clientId=_confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a5256ae2-StreamThread-4-consumer, gro │

    │ cp-ksql-server org.apache.kafka.common.errors.TimeoutException: Failed to send request after 30000 ms.                                                                                                  │

    │ cp-ksql-server [2022-09-19 09:13:49,021] INFO [Consumer clientId=_confluent-ksql-cp-ksql-serverquery_CTAS_MIGRATION_SCHEMA_VERSIONS_1-586b0e83-371a-4def-8056-0237a5256ae2-StreamThread-4-consumer, gro │

    │ cp-ksql-server org.apache.kafka.common.errors.DisconnectException    
```

```
WARN Error forwarding query to node http://cp-ksql-server-7d8764cb88-9vz4p:8088/. Falling back to standby state which may return stale results (io.confluent.ksql.physical.pull.HARouting:313)
cp-ksql-server io.confluent.ksql.rest.client.KsqlRestClientException: Error issuing POST to KSQL server. path:/query
cp-ksql-server     at io.confluent.ksql.rest.client.KsqlTarget.executeSync(KsqlTarget.java:421)
cp-ksql-server     at io.confluent.ksql.rest.client.KsqlTarget.executeRequestSync(KsqlTarget.java:316)
cp-ksql-server     at io.confluent.ksql.rest.client.KsqlTarget.post(KsqlTarget.java:280)
cp-ksql-server     at io.confluent.ksql.rest.client.KsqlTarget.postQueryRequest(KsqlTarget.java:195)
cp-ksql-server     at io.confluent.ksql.rest.server.services.DefaultKsqlClient.makeQueryRequest(DefaultKsqlClient.java:131)
cp-ksql-server     at io.confluent.ksql.physical.pull.HARouting.forwardTo(HARouting.java:352)
cp-ksql-server     at io.confluent.ksql.physical.pull.HARouting.executeOrRouteQuery(HARouting.java:309)
cp-ksql-server     at io.confluent.ksql.physical.pull.HARouting.lambda$executeRounds$6(HARouting.java:193)
cp-ksql-server     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cp-ksql-server     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
cp-ksql-server     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cp-ksql-server     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
cp-ksql-server     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cp-ksql-server     at java.base/java.lang.Thread.run(Thread.java:829)
cp-ksql-server Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: failed to resolve 'cp-ksql-server-7d8764cb88-9vz4p' after 2 queries 
cp-ksql-server     at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
cp-ksql-server     at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
cp-ksql-server     at io.confluent.ksql.rest.client.KsqlTarget.executeSync(KsqlTarget.java:419)
cp-ksql-server     ... 13 more
cp-ksql-server Caused by: java.net.UnknownHostException: failed to resolve 'cp-ksql-server-7d8764cb88-9vz4p' after 2 queries 
```

```
cp-ksql-server [2022-09-16 13:43:39,096] ERROR Error in processing query (io.confluent.ksql.api.server.QuerySubscriber:92)
cp-ksql-server io.confluent.ksql.execution.streams.materialization.MaterializationException: Exhausted standby hosts to try.
cp-ksql-server     at io.confluent.ksql.physical.pull.HARouting.getNodeForRound(HARouting.java:238)
cp-ksql-server     at io.confluent.ksql.physical.pull.HARouting.executeRounds(HARouting.java:206)
cp-ksql-server     at io.confluent.ksql.physical.pull.HARouting.lambda$handlePullQuery$4(HARouting.java:160)
cp-ksql-server     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
cp-ksql-server     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
cp-ksql-server     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
cp-ksql-server     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
cp-ksql-server     at java.base/java.lang.Thread.run(Thread.java:829)
```

### Possible steps

* [ ] bump ksqldb container images from 0.23.1 to 0.28.2
* [ ] bump helm chart
* [ ] address replica communication (unknownhostexception)
   * [ ] check ksql-server.properties against listeners. See book p390. `ksql.advertised.listener`
* [ ] check kafka cluster health 
* [ ] check ksqldb health through observability #1726 
* [ ] tune the metrics ksqldb pipeline for controlling kafka topics and state store sizes
   * [ ] increase partitions (see book p42 and p177)
   * [ ] reduce retentions on 

### Affected releases

* x.y
* earlier versions

**Comment by Guilamb** [comment]
Error using the migration tool described into https://github.com/confluentinc/ksql/issues/9578 along with its workaround setting replicas=3

**Comment by Guilamb** [comment]
```
 Execution time: 0.0170 seconds                                                                                                                                                                          

│ project created                                                                                                                                                                                         

│ number of replicas changed                                                                                                                                                                              

│ OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.                                                               │

│ Initializing migrations metadata                                                                                                                                                                        

│ Creating stream: MIGRATION_EVENTS                                                                                                                                                                       

│ Failed to create stream MIGRATION_EVENTS: io.confluent.ksql.api.client.exception.KsqlClientException: Received 400 response from server: Cannot add stream 'MIGRATION_EVENTS': A stream with the same name already exists. Error code: 40001

│ Execution time: 1.0290 seconds                                                                                                                                                                          

│ migration initialized                                                                                                                                                                                   

│ OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.                                                               

│ Validating current migration state before applying new migrations                                                                                                                                       

│ Could not query MIGRATION_SCHEMA_VERSIONS: java.lang.RuntimeException: Could not decode JSON, expected consistency token: {"errorMessage":{"@type":"generic_error","error_code":50000,"message":"io.confluent.ksql.execution.streams.materialization.MaterializationException: Unable to execute pull query: Exhausted standby hosts to try.Forwarding pull query request failed with error Error issuing POST to KSQL server. path:/query "}}

│ Execution time: 3.5730 seconds       
```

**Comment by gberche-orange** [comment]
We have pause our exploration project of ksqldb. Reopen if we resume in the future.
