### ISSUE TITLE
cf-mysql-broker is tightly coupled to cf cloud controller api

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1736]
### Expected behavior
* As a paas-templates author
* In order to maintain my mariadb service
* I need to deploy it on all iaas (vsphere, openstack-hws, ...)

### Observed behavior
cloudfoundry-mysql-osb-region-2 can't be deployed on openstack-hws because cf-mysql broker is tightly coupled to cf cloud controller api (hosted in region-1)

### Traces and logs
/var/vcap/sys/log/cf-mysql-broker/db_migrate.combined.log
``` 
Net::OpenTimeout: execution expired
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/app/models/cloud_controller_http_client.rb:16:in `get'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/lib/configuration.rb:32:in `cc_api_info'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/lib/configuration.rb:17:in `auth_server_url'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/config/initializers/omniauth.rb:10:in `block in <top (required)>'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `instance_eval'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/rack-1.6.13/lib/rack/builder.rb:55:in `initialize'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/stack.rb:43:in `new'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/stack.rb:43:in `build'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/stack.rb:118:in `each'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/stack.rb:118:in `inject'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/actionpack-4.2.11.3/lib/action_dispatch/middleware/stack.rb:118:in `build'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/engine.rb:502:in `app'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `instance_exec'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:30:in `run'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/initializable.rb:54:in `run_initializers'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/application.rb:352:in `initialize!'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `public_send'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/railtie.rb:194:in `method_missing'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/config/environment.rb:5:in `<top (required)>'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `block in require'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/dependencies.rb:274:in `require'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/application.rb:328:in `require_environment!'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/railties-4.2.11.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/var/vcap/data/packages/cf-mysql-broker/e49cf859a23c47e44f0d51bf0b3350f15ea5d2c1/gem_home/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/var/vcap/packages/ruby-2.7.3-r0.44.0/bin/bundle:23:in `load'
/var/vcap/packages/ruby-2.7.3-r0.44.0/bin/bundle:23:in `<main>'
```

### Solutions
- static routing between region-1 and region-2 (currently applied on vsphere)
- deploy cloud-controller on region-1 and region-2 ?

**Comment by gberche-orange** [comment]
To be coupled with bump of cf-mysql-release and stemcell bump.
