### ISSUE TITLE
concourse IOWait Issue: ramdisk for concourse worker

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#2037]
### Expected behavior

* As a paas-templates operator 
* In order to 
  * use COA / COAB at scale ( > 400 services instances)
  *  
* I need 
  * a smooth scaling of concourse COAB control plane 

### Observed behavior

As of v55, with 400 COAB service instances, observing a huge load and a very high (80%) cpu IO Wait on concourse worker

### Affected releases

* x.y
* earlier versions

**Comment by o-orand** [comment]
It seems RAM disk is too small, there are use cases consuming a lot of disk spaces, like repackaging releases. During repackaging, we clone git repositories, and package bosh releases. So precompile may overload concourse and full workers disks

For instances on BRMC-INT, on `ops-depls`: 
* task `repackage-releases`
```
-rw------- 1 root root  237575332 Aug 17 17:17 bosh-dns-1.36.1.tgz
-rw------- 1 root root     103068 Aug 17 17:17 bosh-dns-aliases-0.0.4.tgz
-rw-r--r-- 1 root root        420 Aug 17 17:50 boshreleases-namespaces.csv
-rw------- 1 root root  221336670 Aug 17 17:18 cf-rabbitmq-506.0.0.tgz
-rw------- 1 root root  102688547 Aug 17 17:19 cf-rabbitmq-multitenant-broker-146.0.0.tgz
-rw------- 1 root root  105388556 Aug 17 17:20 cf-rabbitmq-smoke-tests-172.0.0.tgz
-rw------- 1 root root 1638997471 Aug 17 17:44 concourse-7.8.2.tgz
-rw-r--r-- 1 root root        394 Aug 17 17:50 errors.yml
-rw------- 1 root root   58431200 Aug 17 17:44 helm-kubectl-40.tgz
-rw------- 1 root root   10183467 Aug 17 17:45 node-exporter-5.1.0.tgz
-rw------- 1 root root   52011271 Aug 17 17:45 postgres-44.tgz
-rw------- 1 root root  568306511 Aug 17 17:48 prometheus-29.2.0.tgz
-rw------- 1 root root  220099526 Aug 17 17:49 shared-redis-437.0.36.tgz
-rw------- 1 root root  102406116 Aug 17 17:50 syslog-12.1.5.tgz
```

* task `repackage-releases-fallback`
```
cf-ops-automation/concourse/tasks/repackage_boshreleases_fallback/run.rb
/usr/local/lib/ruby/3.1.0/fileutils.rb:1396:in `copy_stream': No space left on device - copy_file_range (Errno::ENOSPC)
.....
	from /tmp/build/12c3170e/cf-ops-automation/concourse/tasks/repackage_boshreleases_fallback/repackage_releases_fallback.rb:88:in `init_fallback_dir_with_repackaged_dir'
	from /tmp/build/12c3170e/cf-ops-automation/concourse/tasks/repackage_boshreleases_fallback/repackage_releases_fallback.rb:39:in `process'
	from cf-ops-automation/concourse/tasks/repackage_boshreleases_fallback/run.rb:26:in `<main>'
total 1528228
-rw------- 1 root root 237575332 Aug 17 17:50 bosh-dns-1.36.1.tgz
-rw------- 1 root root    103068 Aug 17 17:50 bosh-dns-aliases-0.0.4.tgz
-rw------- 1 root root 221336670 Aug 17 17:50 cf-rabbitmq-506.0.0.tgz
-rw------- 1 root root 102688547 Aug 17 17:50 cf-rabbitmq-multitenant-broker-146.0.0.tgz
-rw------- 1 root root 105388556 Aug 17 17:50 cf-rabbitmq-smoke-tests-172.0.0.tgz
-rw------- 1 root root 897802240 Aug 17 17:50 concourse-7.8.2.tgz

WARNING: fail to repackage all releases, please check /tmp/build/12c3170e/repackaged-releases-fallback/fallback-errors.yml
```

On `master-depls`, task `repackage-releases-fallback`
```
-rw-r--r-- 1 root root 583745353 Aug 17 17:23 pxc-0.55.0.tgz
``` 

Workers memory consumption after feature-bump merge:
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/976115/92186bb1-230b-43fd-9e1f-7d34a8eb8571)

**Comment by o-orand** [comment]
After a worker recreate, gitlab has a huge charge and some concourse resources temporary fail. 
Gitlab cpu load skyrocket to almost 100 !

Gitlab metrics:
![Screen Shot 09-15-23 at 04 49 PM](https://github.com/orange-cloudfoundry/paas-templates/assets/976115/af7631de-f593-40fc-b9a6-eee5e621feee)


Concourse workers on R1-Z2 metrics:
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/976115/8aa84732-fde1-4eac-85e4-1d3519d8141a)

**Comment by JCL38-ORANGE** [comment]
Decision in 56.2.0 : 
- INT / profile disabled
- PPROD / profile enabled
- PROD / profile disabled
