### ISSUE TITLE
java buildpack - mariadb 2.3.0 driver incompatible with flyway

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#299]
### Expected behavior
As a platform user, i expect recent java buildpack to be compatible with mariadb provided in the marketplace

### Observed behavior
Java app using flyway fail to deploy with java buildpack 4.17.2 with cf-mysql 36.0.0 (maria db driver 2.3.0)

```
18:10:20.628: [APP/PROC/WEB.0] 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
18:10:20.628: [APP/PROC/WEB.0] 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
18:10:20.628: [APP/PROC/WEB.0] 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
18:10:20.628: [APP/PROC/WEB.0] 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
18:10:20.628: [APP/PROC/WEB.0] Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.1
18:10:20.628: [APP/PROC/WEB.0] 	at org.flywaydb.core.internal.jdbc.DatabaseType.fromDatabaseProductNameAndPostgreSQLVersion(DatabaseType.java:168)
```
### references
- https://github.com/flyway/flyway/issues/2311
- https://github.com/cloudfoundry/cf-mysql-release (still maria 10.1 in service broker)

**Comment by ldangeard-orange** [comment]
@poblin-orange What is the version of the release or of MariaDB ?

**Comment by ldangeard-orange** [comment]
In cf-mysql-release, there is only connector for C/C++
```sh
mysqlclient/mariadb-connector-c-2.1.0-src.tar.gz:
````
It's the same version since v36

**Comment by islammenshawy** [comment]
Same but with mariadb 1.10.

 o.s.boot.SpringApplication : Application run failed
2019-04-06T12:17:44.895-07:00 [APP/PROC/WEB/0] [OUT] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.1
2019-04-06T12:17:44.895-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
2019-04-06T12:17:44.895-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
2019-04-06T12:17:44.895-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
2019-04-06T12:17:44.895-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
2019-04-06T12:17:44.895-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]
2019-04-06T12:17:44.895-07:00 [APP/PROC/WEB/0] [OUT] at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.4.RELEASE.jar!/:5.1.4.RELEASE]

**Comment by marcoschulte** [comment]
We had the same problem

    FlywayException: Unsupported Database: MariaDB 10.1

Problem was that the new java buildpack bundled the maria db jdbc connector in version >= 2.4. That connector had a codechange which provided MariaDB instead of MySQL as DB name (https://github.com/MariaDB/mariadb-connector-j/commit/5ec5099441a49c677785848132a6099b2beaee99#diff-a6869b202907d71c3d5aecefe6de0ce1R1133).
A DB named MariaDB is only supported in Flyway 6.

The solution is to bundle

    <dependency>
        <groupId>org.mariadb.jdbc</groupId>
        <artifactId>mariadb-java-client</artifactId>
        <version>2.3.0</version>
    </dependency>

with your app. Placing your own connector in your application disables the automatically provided connector of the buildpack (https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-maria_db_jdbc.md)

**Comment by gberche-orange** [comment]
thanks @marcoschulte for sharing your fix. Another short-term workaround without modifying the app is to force usage of the old driver version until the app bumps its dependent libraries (flyway in this case) 

```bash
cf set-env myapp JBP_CONFIG_MARIA_DB_JDBC '{ version: "1.3.0" }'
```
See related [java buidlpack mariadb configuration](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-maria_db_jdbc.md) and [configuration-and-extension through env vars](https://github.com/cloudfoundry/java-buildpack/blob/master/README.md#configuration-and-extension)

**Comment by poblin-orange** [comment]
applied to fix analog issue on db-dumper as of v41
