### ISSUE TITLE
Error : Expected variable '/xx' to be already versioned in deployment 'yy'

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#46]
### Expected behavior

config server / credhub enabled bosh 2 deployment

### Observed behavior

Intermittent error after first deployment failed

```
Task 38522 | 16:59:07 | Error: Expected variable '/tf/openstack_networks_net-cf' to be already versioned in deployment 'cf'

## references 
- #250 
- https://github.com/cloudfoundry/bosh/issues/2046

### Affected release

bosh  264
credhub 1.0.2
#

### Traces and logs

**Comment by gberche-orange** [comment]
See related to bosh story https://www.pivotaltracker.com/story/show/156411329

**Comment by aveyrenc** [comment]
Upstream fixed this bug in those versions:
```console
$ git tag --contains 04dafbdb758205e83f4521d8206235cf8d0adb66
v262.8.0
v266.2.0
v266.3.0
v266.5.0
v266.6.0
v266.7.0
```

No fix for 264/265. An upgrade to BOSH 266 seems to be necessary.

**Comment by poblin-orange** [comment]
happens with:
- variables in cloud-config file (typically master-depls networks, done with terraform)
- 1st deployment ko, seems ok following

**Comment by poblin-orange** [comment]
bosh 266.10.0 in v34 is not enough to fix
workaround:
- modify cloud-config with the exact value instread of the credhub missing reference
- bosh deploy
- restore paas-templates cloud-config (with credhub reference)
- bosh deploy.
This should help the errand to find the correct value

**Comment by o-orand** [comment]
# credhub info
credub get -n '/xxx'
=> <credhub_id>

# bosh db
`bosh ssh <bosh-db>`

As `vcap` user, execute:
```bash
/var/vcap/packages/postgres-9.4/bin/psql -h 127.0.0.1 -U vcap bosh
```

```sql
select name,id from deployments where name = '<depl_name>';

select * from variable_sets where deployment_id = '<depl_id>' order by created_at;
 => choose the latest id

insert into variables (
     variable_id,
     variable_name,
     variable_set_id)
 values (
     '<credhub_id>',
     '/xx',
     <variable_sets_id>);

```

**Comment by poblin-orange** [comment]
TODO:
- cloud-config networks created by terraform (tf-net-cf / tf-net-coab / tf-net-kubo) => rollback to shared/secrets.yml
- test bosh 269

**Comment by poblin-orange** [comment]
v42: bump to bosh 270.3

**Comment by poblin-orange** [comment]
```
ask 1882836

Task 1882836 | 20:06:17 | Preparing deployment: Preparing deployment (00:00:36)
Task 1882836 | 20:06:53 | Preparing deployment: Rendering templates (00:00:32)
Task 1882836 | 20:07:26 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 1882836 | 20:07:28 | Error: wrong chunk size line: 


```

```
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/auth_http_client.rb:24:in `block in get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/auth_http_client.rb:21:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/retryable_http_client.rb:9:in `block in get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/retryable_http_client.rb:8:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/config_server_http_client.rb:20:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:358:in `get_variable_id_and_value_by_name'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:238:in `block in fetch_values_with_deployment'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:223:in `each'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:223:in `fetch_values_with_deployment'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:55:in `interpolate_with_versioning'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:67:in `interpolated_versioned_variables_changed?'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/variables_interpolator.rb:50:in `interpolated_versioned_variables_changed?'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/instance_plan.rb:174:in `network_settings_changed?'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/instance_plan.rb:81:in `changes'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/deployment_plan/instance_plan.rb:55:in `changed?'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_group_updater.rb:31:in `block in update'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_group_updater.rb:26:in `select'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/instance_group_updater.rb:26:in `update'

```

**Comment by poblin-orange** [comment]
```
E, [2019-08-06T15:33:13.317711 #5964] [task:1888846] ERROR -- DirectorJobRunner: undefined method `closed?' for nil:NilClass
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:333:in `stream_check'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:202:in `read_body'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1229:in `block in get'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1518:in `block in transport_request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http/response.rb:165:in `reading_body'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1517:in `transport_request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1479:in `request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:920:in `start'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1470:in `request'
/var/vcap/data/packages/ruby-2.6.3-r0.17.0/9748a2ea55cae0004dc26b99cdf9024c2156cdde/lib/ruby/2.6.0/net/http.rb:1228:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/auth_http_client.rb:24:in `block in get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/auth_http_client.rb:21:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/retryable_http_client.rb:9:in `block in get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:28:in `block in retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `loop'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh_common-0.0.0/lib/common/retryable.rb:26:in `retryer'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/retryable_http_client.rb:8:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/config_server_http_client.rb:20:in `get'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:358:in `get_variable_id_and_value_by_name'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:238:in `block in fetch_values_with_deployment'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:223:in `each'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:223:in `fetch_values_with_deployment'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:55:in `interpolate_with_versioning'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/client.rb:67:in `interpolated_versioned_variables_changed?'
/var/vcap/data/packages/director/930f4d7076d66cb4e3a53f53ee5bd26f54867fef/gem_home/ruby/2.6.0/gems/bosh-director-0.0.0/lib/bosh/director/config_server/variables_interpolator.rb:50:in `interpolated_versioned_variables_changed?'

```

**Comment by JCL38-ORANGE** [comment]
**Workaround completed :**
Step 1 : Connect to bosh database
>/var/vcap/packages/postgres-<version>/bin/psql -h 127.0.0.1 -U vcap bosh
Step 2 : Execute query
insert into variables (variable_id, variable_name, variable_set_id) select (SELECT variable_id FROM variables WHERE variable_name = '${variable}' ORDER BY id DESC LIMIT 1), '${variable}', id from variable_sets vs where vs.deployment_id = (select id from deployments where name = '${deployment}') and not exists (select * from variables v where vs.id = v. variable_set_id and v.variable_name = '${variable}');
Step 3 : Disconnect from bosh database
Step 4 : Trigger the deployment (bosh deploy)
Step 5 : Connect to bosh database
>/var/vcap/packages/postgres-<version>/bin/psql -h 127.0.0.1 -U vcap bosh
Step 6 : Execute query
insert into variables (variable_id, variable_name, variable_set_id) select (SELECT variable_id FROM variables WHERE variable_name = '${variable}' ORDER BY id DESC LIMIT 1), '${variable}', id from variable_sets vs where vs.deployment_id = (select id from deployments where name = '${deployment}') and not exists (select * from variables v where vs.id = v. variable_set_id and v.variable_name = '${variable}');
Step 7 : Recreate the deployment (bosh recreate)

**Comment by poblin-orange** [comment]
as of v42, the woraround has been automated as a errand on micro-depls/bosh-master.

bosh -d bosh-master errands
bosh -d bosh-master run -errand scripting

**Comment by poblin-orange** [comment]
COA concourse level workaround https://github.com/orange-cloudfoundry/cf-ops-automation/issues/290

**Comment by aurelienbouleau** [comment]
> 
> 
> as of v42, the woraround has been automated as a errand on micro-depls/bosh-master.
> 
> bosh -d bosh-master errands
> bosh -d bosh-master run -errand scripting

For clarification, at least in v43 & v44, to run this above errand, man should use exactly:
`bosh -d bosh-master run-errand errand-scripting`

**Comment by gberche-orange** [comment]
To use workaround, the bosh director needs to be configured with the deployment to clean up and the associated keys to clean up

For the example of the `master-depls/logsearch` deployment failing:
* edit the associated bosh director config in secrets repo in `micro-depls/bosh-master/secrets/meta.yml`

```yaml
secrets:
  repair:
    variables: /secrets/openstack_availability_zone|/secrets/openstack_availability_zone_2|/tf/networks_net-cf|/tf/networks_net-is-internet|/tf/networks_net-intranet-2|/tf/networks_net-cfcr-master
    deployments: cf|isolation-segment-internet|isolation-segment-intranet-2|isolation-segment-intranet-1|cfcr-persistent-worker|cfcr
```
* manually launch the errand `bosh -d bosh-master run-errand errand-scripting`
* alternatively, launch the errand via concourse job `micro-depls/pipelines/micro-depls-bosh-generated/jobs/run-manual-errand-bosh-master-errand-scripting`

/CC @skortobi

**Comment by poblin-orange** [comment]
COA 4.2 included in v45 should solve / workaround this issue
