### ISSUE TITLE
dns openstacklocal issue on micro-depls

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#582]
### Observed behavior
On integration environment, while testing target  v44 bosh releases bump.

bosh-dns alias access error on micro-depls.
Seems releated to micro-bosh dhcp setting (other directors dont use dhcp, use config disk for bootstrapping).  See logs in comment

**Comment by poblin-orange** [comment]
===
```
web/1f5e07d8-941f-4db2-a220-4befbffea322:/var/vcap/sys/log/bosh-dns# monit summary
The Monit daemon 5.2.5 uptime: 22h 3m 

Process 'web'                       running
Process 'haproxy'                   running
Process 'route_registrar'           Does not exist
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'node_exporter'             running
Process 'blackbox'                  running
System 'system_localhost'           running
```

=====
route_registrar.stderr.log 

```
panic: nats: connection closed

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc00004e360, 0x79357b, 0x12, 0x801e60, 0xc0000455c0, 0x0, 0x0, 0x0)
        /var/vcap/data/compile/route_registrar/src/code.cloudfoundry.org/lager/logger.go:162 +0x58c
main.main()
        /var/vcap/data/compile/route_registrar/src/code.cloudfoundry.org/route-registrar/main.go:125 +0x99b
panic: nats: no servers available for connection
```
====

bosh_dns.stdout.log

```
[ForwardHandler] 2019/10/22 18:31:10 INFO - handlers.ForwardHandler Request [1] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 4000319000ns
[ForwardHandler] 2019/10/22 18:31:19 DEBUG - error recursing to "192.168.116.166:53": read udp 192.168.116.160:56929->192.168.116.166:53: i/o timeout
[FailoverRecursor] 2019/10/22 18:31:19 INFO - shifting recursor preference: 192.168.116.156:53
[ForwardHandler] 2019/10/22 18:31:19 DEBUG - error recursing to "192.168.116.166:53": read udp 192.168.116.160:41636->192.168.116.166:53: i/o timeout
[FailoverRecursor] 2019/10/22 18:31:19 INFO - shifting recursor preference: 192.168.116.166:53
[ForwardHandler] 2019/10/22 18:31:21 DEBUG - error recursing to "192.168.116.156:53": read udp 192.168.116.160:60998->192.168.116.156:53: i/o timeout
[ForwardHandler] 2019/10/22 18:31:21 INFO - handlers.ForwardHandler Request [28] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 4000483000ns
[ForwardHandler] 2019/10/22 18:31:21 DEBUG - error recursing to "192.168.116.156:53": read udp 192.168.116.160:53959->192.168.116.156:53: i/o timeout
[ForwardHandler] 2019/10/22 18:31:21 INFO - handlers.ForwardHandler Request [1] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 4000424000ns
```

=====
/etc/resolv.conf

```
web/1f5e07d8-941f-4db2-a220-4befbffea322:/var/vcap/sys/log/bosh-dns# cat /etc/resolv.conf 
# This file was automatically updated by bosh-dns
nameserver 169.254.0.2

nameserver 192.168.116.156
nameserver 192.168.116.166
nameserver 192.168.116.254
search openstacklocal
```


====
```
Using environment '192.168.10.10' as user 'poblin' (bosh.read, openid, bosh.admin)

Name       Release(s)           Stemcell(s)                                       Config(s)  Team(s)  
concourse  bosh-dns/1.10.0      bosh-openstack-kvm-ubuntu-xenial-go_agent/315.99  -          -  
           bpm/1.1.3                                                                           
           concourse/5.3.0                                                                     
           haproxy/9.6.2                                                                       
           node-exporter/4.2.0                                                                 
           os-conf/21.0.0                                                                      
           postgres/39                                                                         
           prometheus/25.0.0                                                                   
           routing/0.191.0                                                                     
           shield/7.0.2                                                                        
           syslog/11.4.0                                                                       

1 deployments
```

===
```
bpm-version: "1.0.4"
cf-routing-version: "0.188.0"


bpm-version: "1.1.3"
cf-routing-version: "0.191.0"
```


====
central dns recursor error log

```
[ForwardHandler] 2019/10/22 18:58:21 INFO - handlers.ForwardHandler Request [1] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 10001046000ns
[ForwardHandler] 2019/10/22 18:58:21 INFO - handlers.ForwardHandler Request [28] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 10001019000ns
[ForwardHandler] 2019/10/22 18:58:22 INFO - handlers.ForwardHandler Request [1] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 10000610000ns
[ForwardHandler] 2019/10/22 18:58:22 INFO - handlers.ForwardHandler Request [28] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 10000682000ns
[ForwardHandler] 2019/10/22 18:58:22 INFO - handlers.ForwardHandler Request [28] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 10000579000ns
[ForwardHandler] 2019/10/22 18:58:22 INFO - handlers.ForwardHandler Request [1] [ops-routing-nats.openstacklocal.] 2 [no response from recursors] 10001303000ns
```

====
bosh deployment

```
Name          Release(s)           Stemcell(s)                                       Config(s)  Team(s)  
dns-recursor  bosh-dns/1.10.0      bosh-openstack-kvm-ubuntu-xenial-go_agent/315.99  -          -  
              bpm/1.1.3                                                                           
              node-exporter/4.2.0                                                                 
              ntp/4.2.8p12                                                                        
              os-conf/21.0.0                                                                      
              syslog/11.4.0                                                                       

1 deployments
```

===

patching /etc/resolv.conf unlocks the issue

```
web/1f5e07d8-941f-4db2-a220-4befbffea322:~# cat /etc/resolv.conf 
# This file was automatically updated by bosh-dns
nameserver 169.254.0.2

nameserver 192.168.116.156
nameserver 192.168.116.166
#nameserver 192.168.116.254
#search openstacklocal
```
===

```
web/1f5e07d8-941f-4db2-a220-4befbffea322:~# monit summary
The Monit daemon 5.2.5 uptime: 22h 55m 

Process 'web'                       running
Process 'haproxy'                   running
Process 'route_registrar'           running
Process 'bosh-dns'                  running
Process 'bosh-dns-resolvconf'       running
Process 'bosh-dns-healthcheck'      running
Process 'node_exporter'             running
Process 'blackbox'                  running
System 'system_localhost'           running
```

**Comment by poblin-orange** [comment]
2 causes / context:
- micro-depls cpi was provionning with dhcp
- target dns recursor was to intranet recursor

This does not explain why local bosh-dns aliases get recursed with /etc/resolv.conf

**Comment by poblin-orange** [comment]
- micro-depls cpi configuration changed to use no dhcp (disk type).
- target dns recursor was fixed

merged for v44
