### ISSUE TITLE
COAB delete service instance fails on missing paas-templates dir (possibly failing coab smoke test clean up of old instances)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#844]
### Expected behavior

* As a marketplace user 
* In order to delete a service instance which has internal inconsistencies (e.g. paas-templates service instance missing)
* I need COAB broker to not error on the `cf delete-service-instance` if the service instance is unknown

* [ ] preserve service uprovisionning error if the service instance guid is known (but git push failed to to remove it).

* [ ] make up front git configuration checks and fail fast. See https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/309

### Observed behavior
 
COAB fails with operator facing trace at https://gist.github.com/gberche-orange/96b013be9e273823b87d265cbdd91c3d and the following extract

```
 2020-08-04 14:36:37.174  INFO 19 --- [io-8080-exec-10] o.o.ProcessorChainServiceInstanceService : Unable to delete service with request ServiceBrokerRequest{platformInstanceId='null', apiInfoLocation='api.api-refacted-domain.io/v2/info', originatingIdentity=null}AsyncServiceBrokerRequest{asyncAccepted=true}DeleteServiceInstanceRequest{serviceInstanceId='8264b5f7-aba0-43dd-8c10-67517f785685', serviceDefinitionId='cf-mysql-extended-ondemand-service', planId='plan-coab-mariadb-small'}, caught com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.DeploymentException: Removal fails 
 com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.DeploymentException: Removal fails 
         at com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.StructureGeneratorHelper.removeRecursivelyDirectory(StructureGeneratorHelper.java:111) ~[cf-ops-automation-broker-core-0.30.0.jar:0.30.0] 
         at com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.TemplatesGenerator.removeServiceInstanceDirectory(TemplatesGenerator.java:224) ~[cf-ops-automation-broker-core-0.30.0.jar:0.30.0] 
         at com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.TemplatesGenerator.remove(TemplatesGenerator.java:71) ~[cf-ops-automation-broker-core-0.30.0.jar:0.30.0] 
         at com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.BoshProcessor.preDelete(BoshProcessor.java:149) ~[cf-ops-automation-broker-core-0.30.0.jar:0.30.0] 
         at com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.processors.ProcessorChain.delete(ProcessorChain.java:141) ~[cf-ops-automation-broker-framework-0.30.0.jar:0.30.0] 
         at com.orange.oss.ondemandbroker.ProcessorChainServiceInstanceService.deleteServiceInstance(ProcessorChainServiceInstanceService.java:113) ~[cf-ops-automation-broker-core-0.30.0.jar:0.30.0] 
         at org.springframework.cloud.servicebroker.controller.ServiceInstanceController.deleteServiceInstance(ServiceInstanceController.java:210) [spring-cloud-open-service-broker-core-2.1.2.RELEASE.jar:na] 

 Caused by: java.nio.file.NoSuchFileException: /home/vcap/tmp/paas-templates-clone-1590630849949700708/coab-depls/t_8264b5f7-aba0-43dd-8c10-67517f785685 
         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[na:1.8.0_242] 
         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[na:1.8.0_242] 
         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[na:1.8.0_242] 
         at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[na:1.8.0_242] 
         at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144) ~[na:1.8.0_242] 
         at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[na:1.8.0_242] 
         at java.nio.file.Files.readAttributes(Files.java:1737) ~[na:1.8.0_242] 
         at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) ~[na:1.8.0_242] 
         at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) ~[na:1.8.0_242] 
         at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322) ~[na:1.8.0_242] 
         at java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:72) ~[na:1.8.0_242] 
         at java.nio.file.Files.walk(Files.java:3574) ~[na:1.8.0_242] 
         at java.nio.file.Files.walk(Files.java:3625) ~[na:1.8.0_242] 
         at com.orange.oss.cloudfoundry.broker.opsautomation.ondemandbroker.pipeline.StructureGeneratorHelper.removeRecursivelyDirectory(StructureGeneratorHelper.java:106) ~[cf-ops-automation-broker-core-0.30.0.jar:0.30.0] 
```

### Affected releases

* 47.0.3

**Comment by gberche-orange** [comment]
This possibly fails the coab mysql smoke test when asserting errors logs 
![image](https://user-images.githubusercontent.com/4748380/89626442-bd8dbc80-d899-11ea-8450-39a91cb7dbd3.png)

**Comment by gberche-orange** [comment]
This was occuring on acdc int due to the following scenario:
* misconfiguration of the service broker service instance branch, triggered COAB broker to fail to accept new service instance with message:

```
 [nio-8080-exec-6] o.o.ProcessorChainServiceInstanceService : Unable to create service with request ServiceBrokerRequest{platformInstanceId='null', apiInfoLocation='api.redacted-domain/v2/info', originatingIdentity=Context{platform='cloudfoundry', properties={user_id=8eb11998-acd3-47cf-a7ac-473ac300cdb4}}}AsyncServiceBrokerRequest{asyncAccepted=true}AsyncParameterizedServiceInstanceRequest{parameters={}, context=Context{platform='cloudfoundry', properties={spaceGuid=66d692ed-420b-46da-8054-6aa82dd0c3af, instance_name=cf-mysql-smoketest-1596727743, space_name=coa-cf-mysql-smoke-tests, organizationGuid=93c5f5ad-1718-46b7-9af3-d00499945cb2, organization_name=service-sandbox}}}CreateServiceInstanceRequest{serviceDefinitionId='cf-mysql-ondemand-service', planId='plan-coab-mariadb-small', organizationGuid='93c5f5ad-1718-46b7-9af3-d00499945cb2', spaceGuid='66d692ed-420b-46da-8054-6aa82dd0c3af', serviceInstanceId='96b09cfb-28f4-44c2-8758-694008a2bfa0'}, caught java.lang.RuntimeException: java.lang.IllegalArgumentException: org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/feature-coab-logbins-backup can not be resolved
[...]
2020-08-06T15:29:32.12+0000 [APP/PROC/WEB/0] OUT 2020-08-06 15:29:32.123  WARN 6 --- [nio-8080-exec-7] c.o.o.c.b.o.o.git.SimpleGitManager       : [paas-templates.] caught org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/feature-coab-logbins-backup can not be resolved while cloning into dir: /home/vcap/tmp/paas-templates-clone-382019463921064854 Cleaning up local clone.
```
* this translates into the following user facing UX in the smoke test
```
$ cf create-service mariadb-dedicated small cf-mysql-smoketest-1596727743 -b p-coab-cf-mysql
Creating service instance cf-mysql-smoketest-1596727743 in org service-sandbox / space coa-cf-mysql-smoke-tests as admin...
Service broker error: Internal error condition. Please contact admin to have him check broker logs
FAILED
```
* As a result, CF CC triggers [orphan mitigation](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#orphan-mitigation) and loops on asking to delete the service instance to the broker
   * Note that this service instance guid is not visible in the following repositories
      * secrets repo: the commit was never pushed, because the issue occured during clone (prereq for both repos prior to push)
      * templates repo: the commit was never pushed, because the issue occured during clone 
      * master-depls/cf: 
         * `cf curl /v2/service_instances/96b09cfb-28f4-44c2-8758-694008a2bfa0` returns no such instance, because the instance creation failed synchronously.
         * `cf curl '/v2/events?q=actee:96b09cfb-28f4-44c2-8758-694008a2bfa0` returns no associated events, because the instance creation failed synchronously.
         * cloud controller logs likely include orphan mitigation traces
* The broker systematically fails with a 500 error because the service instance guid is unknown, and logs an error entry.
* Even if new service instances are created successfully, the broker logs are polluted with regular orphan mitigation delete request for the missing service instance guid.

Workakounds: 
 * manually simulate COAB secrets and templates commit for the faulty service instance guid
   * As a result, COAB would accept the `DELETE /v2/service_instances/96b09cfb-` request and end the orphan mitigation loop in CC
 * wait for orphan mitigation to expire (likely one week, see [broker_client_max_async_poll_duration_minutes](https://bosh.io/jobs/cloud_controller_worker?source=github.com/cloudfoundry/capi-release&version=1.97.0#p%3dcc.broker_client_max_async_poll_duration_minutes))

Next steps:
* submit an issue to cloudcontroller ng, to request that orphan mitigation be visible in audit events. 
* Understand how to better control orphan mitigation: period and max duration
   * See https://github.com/cloudfoundry/cloud_controller_ng/issues/1091 for points to orphan mitigation
   * Is it [broker_client_default_async_poll_interval_seconds¶](https://bosh.io/jobs/cloud_controller_worker?source=github.com/cloudfoundry/capi-release&version=1.97.0#p%3dcc.broker_client_default_async_poll_interval_seconds) and [broker_client_max_async_poll_duration_minutes](https://bosh.io/jobs/cloud_controller_worker?source=github.com/cloudfoundry/capi-release&version=1.97.0#p%3dcc.broker_client_max_async_poll_duration_minutes)
