### ISSUE TITLE
Coab redis-extended smoke test failure

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#984]
### Expected behavior

* As a paas-templates operator
* In order to ensure  coab redis-extended is properly configured
* I need it smoke test to be green

### Observed behavior

Same issue than #850 which was not backported on redis-extended, see https://github.com/orange-cloudfoundry/paas-templates-private/pull/226/files

Smoke test fails with 
```
Waiting for app to start...
Start unsuccessful

TIP: use 'cf logs service-probe-app --recent' for more information

FAILED
```

"cf start service-probe-app" command failed with exit code 1 at:

 
```
$ cf logs service-probe-app --recent
[...]
   2020-10-29T14:51:06.33+0100 [CELL/0] OUT Starting health monitoring of container
   2020-10-29T14:51:07.50+0100 [APP/PROC/WEB/0] ERR /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] OUT bundler: failed to load command: rackup (/home/vcap/deps/0/bin/rackup)
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR Bundler::GemNotFound: Could not find cf-app-utils-0.6 in any of the sources
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/spec_set.rb:91:in `block in materialize'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `map!'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/spec_set.rb:85:in `materialize'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/definition.rb:170:in `specs'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/definition.rb:237:in `specs_for'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/definition.rb:226:in `requested_specs'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:108:in `block in definition_method'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/runtime.rb:20:in `setup'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler.rb:107:in `setup'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/bundler/gems/bundler-1.17.3/lib/bundler/setup.rb:20:in `<top (required)>'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
   2020-10-29T14:51:07.55+0100 [APP/PROC/WEB/0] ERR   /home/vcap/deps/0/ruby/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
   2020-10-29T14:51:07.60+0100 [APP/PROC/WEB/0] OUT Exit status 1


### Affected releases

* 48.x
* earlier versions

**Comment by gberche-orange** [comment]
closing as duplicate of #985
